### ISSUE TITLE
标签显示不完整

### ISSUE THREAD

**Issue by 1067237855** [MuiseDestiny/ZoteroStyle#1]
![T12`1ND`~0}JKZM}E)`ML C](https://user-images.githubusercontent.com/104330036/203878829-57fdd16d-2133-4ef0-9ee2-a65d1b186bc6.png)

**Comment by MuiseDestiny** [comment]
尽快写出设置界面，发出后通知你

**Comment by MuiseDestiny** [comment]
安装1.2.0见Readme的设置

**Comment by 1067237855** [comment]
> 安装1.2.0见Readme的设置

![image](https://user-images.githubusercontent.com/104330036/204075824-5e08331d-2bd3-4625-be5c-33a61dd29896.png)


Readme的设置？？？没找到设置方法，不知道怎么设置

**Comment by MuiseDestiny** [comment]
可以把你用的那个标签插件发我吗，或许有冲突

**Comment by MuiseDestiny** [comment]
![Uploading Screenshot_2022-11-26-14-53-40-88_a252b927494330cdc2c8ba3b3f952e5e.jpg…]()
设置

**Comment by MuiseDestiny** [comment]
![Screenshot_2022-11-26-14-53-40-88_a252b927494330cdc2c8ba3b3f952e5e](https://user-images.githubusercontent.com/51939531/204076345-018b794d-f269-4c67-8515-b40d27d360fd.jpg)
设置界面

**Comment by 1067237855** [comment]
> 

我用的zotero自带的标签（在标签栏，输入法直接输入的“🧡💛💙💚💜🖤”），没有用其它的标签插件。
我知道怎么回事了，是因为zoterostyle的**默认** 设置的标签宽度默认为零（Zotero.ZoteroStyle.tagSize=  0）导致的

**Comment by 1067237855** [comment]
> ![Screenshot_2022-11-26-14-53-40-88_a252b927494330cdc2c8ba3b3f952e5e](https://user-images.githubusercontent.com/51939531/204076345-018b794d-f269-4c67-8515-b40d27d360fd.jpg) 设置界面

隐藏的太深了/(ㄒoㄒ)/~~，原来是  鼠标中键  点击  按钮  “>”，然后才能进入“设置界面”
