### ISSUE TITLE
鼠标中键不能设置了 请问该怎么办

### ISSUE THREAD

**Issue by Mashmall** [MuiseDestiny/ZoteroStyle#10]

**Comment by MuiseDestiny** [comment]
设置界面出不来还是设置不生效

**Comment by Mashmall** [comment]
> 就是点击中键没有反应 今天早些时候可以调出来的

**Comment by MuiseDestiny** [comment]
我明天换一台电脑试试

**Comment by Mashmall** [comment]
> 我明天换一台电脑试试

早点休息 很棒的插件！！！

**Comment by MuiseDestiny** [comment]
可以的，或许你卸载后退出Zotero，重新打开Zotero再安装Zotero再重启试试。因为插件被卸载或更新不提示重启（我不会设置这个）。

**Comment by MuiseDestiny** [comment]
鼠标中键的问题，如果真的不可以试试`Shift+P`(如果跟其它插件或者设置没有冲突的话)应该可以调用出界面

**Comment by Mashmall** [comment]
> 可以的，或许你卸载后退出Zotero，重新打开Zotero再安装ZoteroStyle（已更新1.2.3）再重启试试。因为插件被卸载或更新不提示重启（我不会设置这个）。
更新已解决 太强了

**Comment by Mashmall** [comment]
> 鼠标中键的问题，如果真的不可以试试`Shift+P`(如果跟其它插件或者设置没有冲突的话)应该可以调用出界面

可以调出来 就是现在1.2.3不显示进度了 ^.^

**Comment by Mashmall** [comment]
> > 鼠标中键的问题，如果真的不可以试试`Shift+P`(如果跟其它插件或者设置没有冲突的话)应该可以调用出界面
> 
> 可以调出来 就是现在1.2.3不显示进度了 ^.^
你好 已通过chatero刷新进度解决

**Comment by Mashmall** [comment]
> > 鼠标中键的问题，如果真的不可以试试`Shift+P`(如果跟其它插件或者设置没有冲突的话)应该可以调用出界面
> 
> 可以调出来 就是现在1.2.3不显示进度了 ^.^
你好 已通过chatero刷新进度解决
