### ISSUE TITLE
安装122后既往阅读进度条消失

### ISSUE THREAD

**Issue by Darkluna999** [MuiseDestiny/ZoteroStyle#11]
工具-插件 页面问题经排查是操作太快，zotero后台没掉冲突卡住了
但既往进度条。。。

**Comment by MuiseDestiny** [comment]
可以截图看看嘛

**Comment by Darkluna999** [comment]
截图也看不出来呀，就是以前读完不时会有浅蓝进度条吗，现在变回白色了，跟没读一样的，没有了

**Comment by Darkluna999** [comment]
[2022-11-27 00-34-48.zip](https://github.com/MuiseDestiny/ZoteroStyle/files/10096644/2022-11-27.00-34-48.zip)
这个录屏是120测试的，但121 122 效果一致
注意到几点：
1. 安装完 12x 系列xpi包后，并没有出现 restart ，需要手动关闭 zotero 并重新启动，怀疑是否是更新出现问题？
2. 重新安装 115 即可恢复

**Comment by MuiseDestiny** [comment]
感谢你的测试，这很重要。更新后我第一时间通知你

**Comment by MuiseDestiny** [comment]
> 截图也看不出来呀，就是以前读完不是会有浅蓝进度条吗，现在变回白色了，跟刚导入没读是一样的，没有了 附加测试：
> 
> 1. 安装release的115后进度条恢复了
> 2. 120 121 122均没有，且装回115后均恢复
> 3. 然而我没有安装chartero插件。。。。也有进度消失的问题 [进度条消失 #9](https://github.com/MuiseDestiny/ZoteroStyle/issues/9)
> 
> 另外，或许你可以换个icon。。。 以及115无法通过zotero内点击更新的方式拉取github-release来自动更新插件版本，不知道122修改了没有，如果没加可以修改一下拉取更新的方式

哈哈哈，很多东西我还不会改，还在学习，比如怎么设置更新后重启，图标我会换的。

**Comment by Darkluna999** [comment]
更新后重启应该是zot默认的，我的意思是，或许那部分代码本身有问题，部分功能干脆就没生效触发变更

**Comment by MuiseDestiny** [comment]
> 更新后重启应该是zot默认的，我的意思是，或许那部分代码本身有问题，部分功能干脆就没生效触发变更

现在插件都是overlay模式，我用的bootstrap模式（据说是zotero后面要用这个模式，overlay的插件会失效，具体细节我不太清楚），这个模式下我还没发现现有的插件在用，可能是这个原因导致的。

**Comment by Darkluna999** [comment]
确实有这个可能，最近忙别的一直没时间研究这个，但115既然可以正常使用，没道理12x会出问题（逻辑一样的话

**Comment by MuiseDestiny** [comment]
已更新，有好看的图标吗

**Comment by Darkluna999** [comment]
确实修复了，但是更新之后的restart还是没有。。
![](https://user-images.githubusercontent.com/53258301/204141548-1b8b1a95-1889-4189-922f-68bb7022a93e.png)
pandoc插件的，我觉着还挺符合的，修改修改啥的？

**Comment by MuiseDestiny** [comment]
完了，忘了改logo，就发布了，让你失望了

**Comment by Darkluna999** [comment]
啊哈哈哈哈哈哈，那就期待后续啦
