### ISSUE TITLE
无法显示标签

### ISSUE THREAD

**Issue by cyjiaoo** [MuiseDestiny/ZoteroStyle#12]
win11系统，安装插件后，tag一开始和文章名称重叠，点击之后消失，之后重新加标签也不会再显示。

**Comment by Mashmall** [comment]
首次安装的话需要 设置Zotero.ZoteroStyle.tagSize=8 显示

**Comment by MuiseDestiny** [comment]
> 首次安装的话需要 设置Zotero.ZoteroStyle.tagSize=8 显示

谢谢答复，这是一个bug，现在修复了，没设置tagSize会默认为5

**Comment by MuiseDestiny** [comment]
> win11系统，安装插件后，tag一开始和文章名称重叠，点击之后消失，之后重新加标签也不会再显示。

更新试试

**Comment by cyjiaoo** [comment]
好呢我再试试，谢谢！



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月27日 10:32 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [MuiseDestiny/ZoteroStyle] 无法显示标签 (Issue #12) |

win11系统，安装插件后，tag一开始和文章名称重叠，点击之后消失，之后重新加标签也不会再显示。

更新试试

**Comment by Mashmall** [comment]
> tagSize

请问在xpi文件里如何修改默认的tagSize

**Comment by MuiseDestiny** [comment]
我已修改好

**Comment by Mashmall** [comment]
> 我已修改好

想用一下旧版本 旧版本不需要刷新就可以显示进度 但是旧版本的tagSize有点小 想修改一下

**Comment by MuiseDestiny** [comment]
xpi用压缩包解压找到indrx.js搜索5em改成你想要的，然后这个压缩包是可以作为插件安装的

**Comment by Mashmall** [comment]
> xpi用压缩包解压找到indrx.js搜索5em改成你想要的，然后这个压缩包是可以作为插件安装的

已解决 好棒的插件
