### ISSUE TITLE
同步问题

### ISSUE THREAD

**Issue by Hundredl** [MuiseDestiny/ZoteroStyle#13]
更换电脑如何同步阅读进度信息呢，信息同步可以通过zotero/webapi自动实现吗！
ps：太喜欢了这个插件了，开发者好棒～

**Comment by MuiseDestiny** [comment]
我正在写参考文献功能，写完就会考虑怎么完美同步，因为参考文献也有许多信息需要同步

**Comment by MuiseDestiny** [comment]
支持了，但或许有一些未知问题。
