### ISSUE TITLE
希望shift+P快捷的搜索框可以改为命令面板加搜索框

### ISSUE THREAD

**Issue by hujie12306** [MuiseDestiny/ZoteroStyle#16]
图为obsidian，很方便
![image](https://user-images.githubusercontent.com/61086637/204524662-20fc123d-0de5-4954-b045-06197d2ac5a9.png)

**Comment by MuiseDestiny** [comment]
可以的后面会这么发展，现在只是雏形

**Comment by MuiseDestiny** [comment]
obsidian是什么快捷键啊，目前zotero里不能使用ctrl键，其它应该都可以

**Comment by hujie12306** [comment]
obsidian是一个笔记软件，图片是obsidian的命令面板

**Comment by MuiseDestiny** [comment]
> > obsidian是什么快捷键啊，目前zotero里不能使用ctrl键，其它应该都可以
> 
> obsidian是一个笔记软件，图片是obsidian的命令面板
obsidian里怎么调出这个命令面板，有快捷键吗

**Comment by hujie12306** [comment]
> > > obsidian是什么快捷键啊，目前zotero里不能使用ctrl键，其它应该都可以
> > 
> > 
> > obsidian是一个笔记软件，图片是obsidian的命令面板
> > obsidian里怎么调出这个命令面板，有快捷键吗

默认为ctrl+P
obsidian里所有命令可以自定义快捷键，我给命令面板增加了alt+w快捷键（单手更好按）

**Comment by hujie12306** [comment]
> 试了下，是ctrl+P

哈哈，慢了一步

**Comment by MuiseDestiny** [comment]
> > 试了下，是ctrl+P
> 
> 哈哈，慢了一步

它好丝滑，我肯定做不到它这样，但尽力取模仿

**Comment by hujie12306** [comment]
> > > 试了下，是ctrl+P
> > 
> > 
> > 哈哈，慢了一步
> 
> 它好丝滑，我肯定做不到它这样，但尽力取模仿

是的，流畅好用+丰富的插件系统，强烈推荐

其实，这个命令面板可能由zotero官方来开发更为合适，这样可以让所有插件的命令都接入，那就太棒了

**Comment by MuiseDestiny** [comment]
> > > > 试了下，是ctrl+P
> > > 
> > > 
> > > 哈哈，慢了一步
> > 
> > 
> > 它好丝滑，我肯定做不到它这样，但尽力取模仿
> 
> 是的，流畅好用+丰富的插件系统，强烈推荐
> 
> 其实，这个命令面板可能由zotero官方来开发更为合适，这样可以让所有插件的命令都接入，那就太棒了

对，个人做不到官方这么好

**Comment by 1067237855** [comment]
![image](https://user-images.githubusercontent.com/104330036/204685816-986215c4-7fbf-49ca-8953-e0c38d81107d.png)

**Comment by 1067237855** [comment]
![Uploading Quicker_20221130_093052.png…]()


> ![image](https://user-images.githubusercontent.com/104330036/204685816-986215c4-7fbf-49ca-8953-e0c38d81107d.png)

对小白来说，编程命令太复杂了，每次使用都要去GitHub查找具体怎么用，这就很麻烦。希望尽量减少编程语言，使用自然语言（例如，输入“标签”自动显示跟标签有关的命令，输入“颜色”自动显示跟颜色有关的命令）

**Comment by hujie12306** [comment]
> 方向键上，就会有所有支持的命令提示。感觉现在提供的这些设置都根据自己喜好配置一遍就行了，比如标签想放在左边执行一次tagPosition=1就可以了。后面如果有常用功能加进去尽量仿照Obsidian。

确实，之前不知道可以方向键，都是在手打命令，现在也很方便了

**Comment by 1067237855** [comment]
> 方向键上，就会有所有支持的命令提示。感觉现在提供的这些设置都根据自己喜好配置一遍就行了，比如标签想放在左边执行一次tagPosition=1就可以了。后面如果有常用功能加进去尽量仿照Obsidian。
![image](https://user-images.githubusercontent.com/104330036/204697029-62a06197-fca1-4dbf-b7ed-261a6192bccd.png)

**Comment by AlexLee1992** [comment]
问一下这个快捷搜索栏是 shift+P 打开吗？为什么 Mac 上按这两个键不能打开啊？

**Comment by MuiseDestiny** [comment]
> 问一下这个快捷搜索栏是 shift+P 打开吗？为什么 Mac 上按这两个键不能打开啊？

是在英文模式下，光标不在搜索框里闪烁的时候。

初次打开zotero，搜索框会获得焦点，这时候shift+p是没用的。点击任意一个文献条目，搜索框失去焦点，再按快捷键就可以了。
