### ISSUE TITLE
功能需求：标签显示增加zotero默认显示方式

### ISSUE THREAD

**Issue by hujie12306** [MuiseDestiny/ZoteroStyle#17]
个人更喜欢zotero默认显示方式（因为更省空间），但需要zotero style 的其他功能，希望可以支持zotero默认显示方式

**Comment by MuiseDestiny** [comment]
好的，就是标签还是放原来的位置。那还要不要圆形状呢（原来是圆角正方形）。

**Comment by hujie12306** [comment]
> 好的，就是标签还是放原来的位置。那还要不要圆形状呢（原来是圆角正方形）。

这个都可以，怎么简单怎么来吧，谢谢开发者啦！

**Comment by MuiseDestiny** [comment]
安装1.3.2解决这个问题

**Comment by hujie12306** [comment]
完美
![image](https://user-images.githubusercontent.com/61086637/204696136-92c3994a-f4c1-4736-ac1b-f4e6505323ff.png)

**Comment by yonglong2020** [comment]
请问tagPosition=0这个要怎么设置，我在编辑器中没有找到这个属性
