### ISSUE TITLE
自定义按钮，可以将某一列变宽

### ISSUE THREAD

**Issue by 1067237855** [MuiseDestiny/ZoteroStyle#2]
![image](https://user-images.githubusercontent.com/104330036/203879360-3bf7a0ad-ad9b-4c7e-9ca6-9ed1c87b3251.png)

因为每个人的使用习惯不同，所以需要变宽的列就不同。如果可以自定义“>”该按钮的话，使用起来更方便

**Comment by MuiseDestiny** [comment]
感谢提出，在规划中，发布新版我将通知你

**Comment by 1067237855** [comment]
> 感谢提出，在规划中，发布新版我将通知你
![image](https://user-images.githubusercontent.com/104330036/203900332-972d86ef-75c2-4c3a-8877-ae1e920f658e.png)

**Comment by MuiseDestiny** [comment]
> > 感谢提出，在规划中，发布新版我将通知你
> > ![image](https://user-images.githubusercontent.com/104330036/203900332-972d86ef-75c2-4c3a-8877-ae1e920f658e.png)

1.2.1现在支持定义这个了
你可以根据你的喜好设置几组,设置历史可以方便查看,你可以输入命令在`各种显示不同字段面板`之间来回切换
Zotero.ZoteroStyle.constantFields=['hasAttachment', 'title'] - 这个显示那个回形针和标题
Zotero.ZoteroStyle.constantFields=['title'] - 仅仅显示标题
Zotero.ZoteroStyle.constantFields=['title', 'year'] - b标题和年份

**Comment by 1067237855** [comment]
> > > 感谢提出，在规划中，发布新版我将通知你
> > > ![image](https://user-images.githubusercontent.com/104330036/203900332-972d86ef-75c2-4c3a-8877-ae1e920f658e.png)
> 
> 1.2.1现在支持定义这个了 你可以根据你的喜好设置几组,设置历史可以方便查看,你可以输入命令在`各种显示不同字段面板`之间来回切换 Zotero.ZoteroStyle.constantFields=['hasAttachment', 'title'] - 这个显示那个回形针和标题 Zotero.ZoteroStyle.constantFields=['title'] - 仅仅显示标题 Zotero.ZoteroStyle.constantFields=['title', 'year'] - b标题和年份

PS：字段列表自由组合
