### ISSUE TITLE
能不能在安装Chartero的情况下，也渲染Style的进度条

### ISSUE THREAD

**Issue by zyx335588** [MuiseDestiny/ZoteroStyle#24]
目前在安装[Chartero](https://github.com/volatile-static/Chartero)插件后[ZoteroStyle](https://github.com/MuiseDestiny/ZoteroStyle)插件不渲染进度条，不知道能不能添加恢复Style插件进度条的选项。
本人比较喜欢的Chartero的提取图片的功能，但不怎么用它的仪表盘。因为一般更多的是关注信息面板，要看进度还需要切换面板，加之个人并不需要指导阅读各页的精确时间，只需要大致了解一下阅读进度，感觉Style插件的直接显示相对直观一些，正好能满足这个需求。

**Comment by MuiseDestiny** [comment]
已经实现，请更新

**Comment by MuiseDestiny** [comment]
因为style已经实现了数据储存在笔记，所以同步不依赖chart了

**Comment by zyx335588** [comment]
太棒了，点赞👍👍

**Comment by coisini-95** [comment]
> 已经实现，请更新

大佬，为什么这个进度条还是不能一直渲染在条目上呢

**Comment by MuiseDestiny** [comment]
> > 已经实现，请更新
> 
> 大佬，为什么这个进度条还是不能一直渲染在条目上呢

以前Chartero记录的数据，刷新后渲染出来点击会消失。从安装新style插件起后面的记录将由style负责收集储存在笔记（为了同步），这些进度就不会消失了。

所以以前由chartero负责储存的数据，style没有读取，自然会消失的。

**Comment by coisini-95** [comment]
> > > 已经实现，请更新
> > 
> > 
> > 大佬，为什么这个进度条还是不能一直渲染在条目上呢
> 
> 以前Chartero记录的数据，刷新后渲染出来点击会消失。从安装新style插件起后面的记录将由style负责收集储存在笔记（为了同步），这些进度就不会消失了。
> 
> 所以以前由chartero负责储存的数据，style没有读取，自然会消失的。

我装了新版style插件后，再点击了看了几个文献，还是不会显示唉，还以为是那个小箭头按键的原因，但我右键了几次也没有

**Comment by MuiseDestiny** [comment]
你看下有没有这个条目
![image](https://user-images.githubusercontent.com/51939531/205431134-ca0fcf61-b9d1-4ddb-974a-0f3257ca67d9.png)

**Comment by coisini-95** [comment]
> 你看下有没有这个条目 ![image](https://user-images.githubusercontent.com/51939531/205431134-ca0fcf61-b9d1-4ddb-974a-0f3257ca67d9.png)

![图片](https://user-images.githubusercontent.com/78250635/205431169-94baa341-eb1a-4719-8dcb-f8722873f141.png)
有的，我还卸载重装插件好几次，一直没有，不知道咋回事，不过这个记录一直有，就是没渲染，不知道是不是插件冲突原因

**Comment by MuiseDestiny** [comment]
重启试试呢，第一次运行会迁移数据

**Comment by coisini-95** [comment]
> 重启试试呢，第一次运行会迁移数据

软件重启过几次，电脑也重启过一次，一直没渲染，我再重启一下

**Comment by MuiseDestiny** [comment]
比如看一篇`新文献`，看第一页30s左右，然后这个ZoteroStyle里应该会有你看的文献对应标题的笔记，然后看看`新文献`有没有进度。

如果还没有的话，你可以
![image](https://user-images.githubusercontent.com/51939531/205431415-578a1618-1cf2-4337-a42d-d8991e96915c.png)
点击图中任意一个笔记，截图我看看右边的内容。

**Comment by coisini-95** [comment]
![图片](https://user-images.githubusercontent.com/78250635/205431528-01868d9d-3553-4c07-a5e7-0feeb41e6f18.png)
有进度的，点进去几秒再关闭就有新的文献纪录，但是不会渲染上去，这个图是我装的老插件的（没有加命令行设置之前的），有渲染，卸载老版再重启装1.3.4版本后就没有渲染了

**Comment by MuiseDestiny** [comment]
可以装新的，然后截图我看下`帮助->报告错误`里面的信息嘛
![image](https://user-images.githubusercontent.com/51939531/205431648-56f91ab8-bccd-4d80-86a6-8110252bc79b.png)

**Comment by coisini-95** [comment]
嗯嗯，我不知道那个有用，截了个长图
[JavaScript Error: "this.collectionTreeRow is undefined" {file: "chrome://zotero/content/itemTree.js" line: 208}]

[JavaScript Error: "TypeError: this.collectionTreeRow is undefined" {file: "chrome://zotero/content/itemTree.js" line: 208}]

[JavaScript Error: "message is undefined" {file: "resource://zotero/note-editor/editor.js" line: 69711}]

Security Error: Content at moz-nullprincipal:{30e7da37-4229-4213-9c2f-148f8bf3f7a0} may not load or link to chrome://chartero/content/TabPanel/index.html.

Security Error: Content at moz-nullprincipal:{30e7da37-4229-4213-9c2f-148f8bf3f7a0} may not load or link to chrome://chartero/content/TabPanel/index.html.

[JavaScript Error: "TypeError: style.getCiteProc is not a function with 'http://www.zotero.org/styles/GB-T-7714-2015-numeric-aulower-bilan-CE'"]

[JavaScript Error: "TypeError: style.getCiteProc is not a function with 'http://www.zotero.org/styles/GB-T-7714-2015-numeric-aulower-bilan-CE'"]

[JavaScript Error: "TypeError: style.getCiteProc is not a function with 'http://www.zotero.org/styles/GB-T-7714-2015-numeric-aulower-bilan-CE'"]

[JavaScript Error: "TypeError: style.getCiteProc is not a function with 'http://www.zotero.org/styles/GB-T-7714-2015-numeric-aulower-bilan-CE'"]

version => 6.0.18, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => zh-CN, appName => Zotero, appVersion => 6.0.18, extensions => ZoteroQuickLook (1.4.2, extension), Zutilo Zotero 工具箱 (3.10.0, extension), Sci-Hub Plugin for Zotero (1.4.4, extension), ZotFile (5.1.2.999, extension), Zotero Theme (0.0.9, extension), Zotero LibreOffice Integration (6.0.3.SA.6.0.18, extension), Zotero Word for Windows Integration (6.0.2.SA.6.0.18, extension), Delitem (0.0.20, extension), Zotero Tag (0.3.0, extension), Zotero PDF Translate (0.9.4, extension), Chartero (1.3.0, extension), Zotero Better Notes (0.7.28, extension), Jasminum (0.2.3, extension), Zotero更新期刊信息 (0.3.6, extension), Zotero Style (1.3.4, extension), Shockwave Flash (34.0.0.277, plugin), Zotero Citation Update (0.0.1, extension, disabled), Zotero IF (1.4.7, extension, disabled)
![图片](https://user-images.githubusercontent.com/78250635/205431741-d6d9fd9f-1d6e-4c9f-875b-d0adcf5389bc.png)

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/205431835-bcdfc9aa-4df1-4457-819f-9be1618f9aad.png)
`Zotero.ZoteroStyle.events.record`看下你的输出，刚刚的错误里没有关于style的报错。

这个窗口在`工具->开发者->run javascript`

**Comment by coisini-95** [comment]
![图片](https://user-images.githubusercontent.com/78250635/205432006-fa755bd1-0fd9-404f-b031-e0ff4fa65dee.png)

**Comment by MuiseDestiny** [comment]
天哪，是有数据的就是不渲染，我检查检查

**Comment by MuiseDestiny** [comment]
<https://gitee.com/MuiseDestiny/BiliBili/blob/master/zotero-style.xpi>试试这个

**Comment by MuiseDestiny** [comment]
如果还不行，麻烦你把这个信息发给我，如果怕泄露隐私，可以发到我的邮箱33699@outlook.com，我重现一下你运行过程看会出现什么问题
![image](https://user-images.githubusercontent.com/51939531/205432759-9c8139a2-e0a8-4581-a1e5-f3ac2d19d2d0.png)
Zotero.Prefs.get("Zotero.ZoteroStyle.record")

**Comment by coisini-95** [comment]
> https://gitee.com/MuiseDestiny/BiliBili/blob/master/zotero-style.xpi试试这个

这个我装不了，显示zotero版本不兼容。
我再装上1.3.4的style后，要不要再点几个文献看看，因为卸载过了会不会记录没了

**Comment by MuiseDestiny** [comment]
可以，你看看试试

**Comment by coisini-95** [comment]
> 可以，你看看试试
![图片](https://user-images.githubusercontent.com/78250635/205434238-c9cfb760-fc32-4a11-9285-9e53b6f99b31.png)
奇怪，我重新装了后，点了好几个文献看，这个运行后的一直不变

**Comment by MuiseDestiny** [comment]
> > 可以，你看看试试
> > ![图片](https://user-images.githubusercontent.com/78250635/205434238-c9cfb760-fc32-4a11-9285-9e53b6f99b31.png)
> > 奇怪，我重新装了后，点了好几个文献看，这个运行后的一直不变

右边全复制下来发给我，谢谢~

**Comment by coisini-95** [comment]
{"冷却速度对1.35%Si无取向硅钢热轧退火织构的影响":{"0":10,"total":6},"Influence of the angle between cold rolling direction and hot rolling direction on the texture evolution of non-oriented electrical steels":{"0":5,"total":5},"电工钢":{"0":15,"4":5,"7":15,"18":55,"41":110,"42":70,"99":5,"100":5,"total":682},"2021年中国电工钢产业发展报告":{"3":5,"4":5,"5":10,"7":20,"8":45,"10":10,"11":15,"12":5,"13":50,"14":70,"15":5,"20":5,"23":5,"24":5,"27":5,"28":5,"29":5,"31":5,"33":5,"34":5,"37":5,"40":5,"41":320,"42":305,"43":170,"44":10,"total":80},"电工钢的材料学原理":{"3":20,"4":45,"5":15,"13":5,"25":5,"29":65,"30":35,"31":10,"253":5,"254":55,"255":5,"258":5,"259":10,"260":80,"261":5,"262":5,"263":15,"total":633},"无取向硅钢的织构与磁性":{"4":15,"10":30,"24":10,"35":5,"38":15,"96":25,"116":5,"118":10,"119":5,"123":5,"127":15,"total":177},"无取向硅钢特殊路径轧制工艺及组织性能研究":{"16":10,"17":60,"total":84},"无取向硅钢W800生产过程中洁净度研究":{"0":5,"14":75,"total":64},"中低牌号无取向硅钢组织和磁性能的优化":{"17":15,"20":55,"total":85},"低牌号无取向硅钢的织构研究":{"3":10,"total":107},"无取向硅钢织构与性能的研究":{"19":10,"25":5,"total":155},"高牌号无取向电工钢免常化处理的基础研究":{"3":10,"total":58},"高牌号无取向硅钢中夹杂物/析出物的表征及硫化物对组织影响的研究":{"0":5,"16":65,"17":10,"total":79},"CSP工艺下无取向电工钢50W800的开发及质量控制":{"10":5,"14":5,"18":20,"total":60},"Evaluating the Suitability of Partial Recrystallization as a Strengthening Method for Thin-Gauge, High-Strength Non-Orientated Electrical Steel":{"0":5,"1":45,"total":12},"Ultrathin-gauge high silicon non-oriented electrical steel with high permeability and low core loss fabricated by optimized two-stage cold rolling method":{"0":15,"1":15,"11":5,"14":5,"total":17},"二次冷轧压下率对高牌号无取向硅钢组织结构和磁性能的影响":{"0":10,"total":4},"High-permeability and thin-gauge non-oriented electrical steel through twin-roll strip casting":{"0":5,"1":20,"total":11},"The evolution of cube ({001}<100>) texture in non-oriented electrical steel":{"1":5,"total":15},"Texture Evolution of a Non-oriented Electrical Steel Cold Rolled at Directions Different from the Hot Rolling Direction":{"1":10,"total":16},"Texture evolution during skew cold rolling and annealing of a non-oriented electrical steel containing 0.9 wt% silicon":{"1":5,"2":10,"total":20},"异步轧制下无取向硅钢的冷轧织构":{"0":5,"3":5,"total":4},"异步轧制取向硅钢晶粒长大过程中的再结晶织构演变":{"14":20,"16":5,"25":5,"29":5,"30":5,"31":5,"32":5,"35":20,"total":82},"异步轧制对硅钢薄带织构和磁性能影响机理的研究":{"15":5,"16":10,"17":40,"26":5,"total":69},"异步轧制和退火工艺对无取向硅钢组织、织构及性能的影响":{"12":5,"total":61},"常化处理对50W800电工钢组织、织构与磁性的影响":{"0":5,"1":10,"2":170,"3":20,"4":5,"5":25,"6":45,"total":8},"常化温度对热轧无取向硅钢组织与磁性能的影响":{"0":10,"1":55,"2":20,"total":4},"Effect of rolling methods on microstructure, recrystallization texture and magnetic properties in a Fe–2.5%Si–0.52%Al non-oriented electrical steel":{"0":5,"total":9},"双辊铸轧中牌号无取向电工钢组织、性能的研究":{"45":5,"total":86}}

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/205435058-b2c47305-ba4a-4c24-9884-64d72401349d.png)
数据没问题，我这边可以渲染，你那里不能渲染问题可能不出在这。

**Comment by MuiseDestiny** [comment]
Zotero.ZoteroStyle.progressOpacity=.7
      Zotero.ZoteroStyle.tagSize=5
      Zotero.ZoteroStyle.tagPosition=4
      Zotero.ZoteroStyle.tagAlign=left
      Zotero.ZoteroStyle.progressColor=#5AC1BD
      Zotero.ZoteroStyle.constantFields=['hasAttachment', 'title']

你试试把这些命令重新输入一遍呢

**Comment by MuiseDestiny** [comment]
因为可能是某个参数误触设置错了，比如opacity设置成0就始终不会渲染进度条（其实渲染了只是全透明了），所以把这些默认参数命令都统统执行一遍或许有效。

吐槽一句：现在输入命令方式太不科学了。

**Comment by MuiseDestiny** [comment]
补充，还有这个`Zotero.ZoteroStyle.progressColor=#FF9E9E`（后面颜色可以按照心情来）

**Comment by coisini-95** [comment]
> 补充，还有这个`Zotero.ZoteroStyle.progressColor=#FF9E9E`（后面颜色可以按照心情来）

没得用，命令输了一遍，然后重装了插件，没用，不晓得撒原因

**Comment by MuiseDestiny** [comment]
> > 补充，还有这个`Zotero.ZoteroStyle.progressColor=#FF9E9E`（后面颜色可以按照心情来）
> 
> 没得用，命令输了一遍，然后重装了插件，没用，不晓得撒原因

![image](https://user-images.githubusercontent.com/51939531/205436311-13221bf4-0318-4738-8a97-c0604f8c8fba.png)
最后尝试这一次，不行就放弃了，这里run javascript，输入下面代码，截图我看看结果。


res = []
for (let k of [
    "Zotero.ZoteroStyle.progressOpacity",
    "Zotero.ZoteroStyle.tagSize",
    "Zotero.ZoteroStyle.tagPosition",
    "Zotero.ZoteroStyle.tagAlign",
    "Zotero.ZoteroStyle.progressColor",
    "Zotero.ZoteroStyle.constantFields",
    "Zotero.ZoteroStyle.progressColor"
]) {
    
    res.push([k, Zotero.Prefs.get(k)])
}
res

**Comment by coisini-95** [comment]
![图片](https://user-images.githubusercontent.com/78250635/206399660-0bc82b9c-3bac-4868-b257-005a129e4cd4.png)
不好意思，回家隔离了五天，才看到。
然后我在家里电脑上搞zotero，数据同步过去后，装上这个插件有进度条，不知道为什么就是笔记本没用

**Comment by MuiseDestiny** [comment]
undefined的都需要重新设置一下，更新最新版吧，不那么反人类了，不需要命令

**Comment by coisini-95** [comment]
> undefined的都需要重新设置一下，更新最新版吧，不那么反人类了，不需要命令

离谱的是，在笔记本上我定义进度条颜色输入#7FE9DE，按enter键没反应，下面的颜色示例也没变，但是在台式电脑上定义就正常。这个异常我早就发现了，就是复制作者你的命令粘贴进去，按enter没反应，这是什么原因，有没有可能是电脑上其它软件影响了？

**Comment by MuiseDestiny** [comment]
黑人问号脸：我也不清楚，好奇怪

**Comment by coisini-95** [comment]
![图片](https://user-images.githubusercontent.com/78250635/206408513-9ad522bb-fbb4-4ea7-b785-2ddfe8a61309.png)
这是我定义了颜色#7FE9DE，按了三下enter键，然后出现了三个错误，这是啥意思

**Comment by MuiseDestiny** [comment]
可以试重启zotero说是获取task失败，最好重新安装下插件

**Comment by coisini-95** [comment]
重启软件、重装插件、重启系统后都没得用（捂脸笑），无语了，按enter键一直没用，这个插件是需要什么系统级的框架吗（捂脸笑）

**Comment by MuiseDestiny** [comment]
https://www.zotero.org/support/kb/profile_directory
在这里找对应目录

**Comment by MuiseDestiny** [comment]
> ![图片](https://user-images.githubusercontent.com/78250635/206408513-9ad522bb-fbb4-4ea7-b785-2ddfe8a61309.png) 这是我定义了颜色#7FE9DE，按了三下enter键，然后出现了三个错误，这是啥意思

复现了这个错误，等我修复

**Comment by coisini-95** [comment]
> 1.4.3试试，有个逻辑被我误删了

可以啦，感谢大佬，进度条也出现了

**Comment by MuiseDestiny** [comment]
> > 1.4.3试试，有个逻辑被我误删了
> 
> 可以啦，感谢大佬，进度条也出现了

我哭死，终于解决了
