### ISSUE TITLE
功能建议：希望在以后的版本里加上删除历史命令的操作

### ISSUE THREAD

**Issue by Mashmall** [MuiseDestiny/ZoteroStyle#25]
您好作者，目前为止软件很好用，但是由于之前多次尝试导致历史的命令很多，但目前为止常用的命令又比较靠前调用起来比较麻烦，请问是否有清楚命令的操作，或者在以后的版本里面假如，谢谢。

**Comment by MuiseDestiny** [comment]
delete可以删除的，但是没介绍，不好意思~

**Comment by Mashmall** [comment]
可惜 我居然没有尝试一下 谢谢

**Comment by Mashmall** [comment]
> delete可以删除的，但是没介绍，不好意思~

你好 我尝试了一下 但是不知道是我操作不到位还是咋的delate之后 再次打开应用还是有历史的命令存在

**Comment by MuiseDestiny** [comment]
> > delete可以删除的，但是没介绍，不好意思~
> 
> 你好 我尝试了一下 但是不知道是我操作不到位还是咋的delate之后 再次打开应用还是有历史的命令存在

有一些常驻的命令，我设置每次都显示了（为了方便知道支持什么命令）。我打算后面不用这种命令了，用Obsidian类似的交互。

**Comment by Mashmall** [comment]
> > > delete可以删除的，但是没介绍，不好意思~
> > 
> > 
> > 你好 我尝试了一下 但是不知道是我操作不到位还是咋的delate之后 再次打开应用还是有历史的命令存在
> 
> 有一些常驻的命令，我设置每次都显示了（为了方便知道支持什么命令）。我打算后面不用这种命令了，用Obsidian类似的交互。

嗯嗯 十分期待 万分感激
