### ISSUE TITLE
修改阅读进度笔记内容，重启之后进度条归零

### ISSUE THREAD

**Issue by muxinxy** [MuiseDestiny/ZoteroStyle#32]
重启zotero之后进度条归零，打开之前的文献，zotero style下面会生成一条重名的笔记，这样同一篇文献就有两条笔记了，而且进度重新开始。
另外，因为zotero style和chartero进度不一致，想要手动修改zotero style下面的笔记，但是改了不起作用。
chartero的进度条会因为点击条目而消失，所以只能依赖zotero style。

**Comment by MuiseDestiny** [comment]
改了之后重启会重新读取，另外你可以看看`未分类目录`下有几个ZoteroStyle条目，如果有重复可以选择删除一个。因为以前用title作为key记录文献，新版本用zotero内部的key，所以可能会出现你说的重复`ZoteroStyle`下的笔记。你可以试试新打开一个文献，然后阅读试试，生成的对应笔记应该是唯一的。

**Comment by muxinxy** [comment]
修改了笔记也会影响key吗，修改之后再打开相同文献就会生成重复笔记

**Comment by MuiseDestiny** [comment]
修改笔记不回影响key，key是`ZoteroStyle`的key，下面的笔记也有自己的key
逻辑是：
搜索文献库有没有ZoteroStyle条目，
    有 -> 根据key得到条目 -> 得到后记录条目的key，下次就不搜索了
                                          -> 得不到条目（有可能被彻底删了），创建条目，并记录创建条目的key

    无 -> 创建条目，记录key，下次直接读取


但是存在一个旧数据（本来不以笔记形式储存，无法同步）迁移到笔记中（用于以后的同步），而且还涉及到title->key的转换，这一些列我不能保证旧的阅读数据正确被读取（尽管我测试可以的，不排除存在其它bug），但新阅读的数据一定是无误的。

**Comment by MuiseDestiny** [comment]
等我画个流程图

**Comment by MuiseDestiny** [comment]
readme中更新，可以排查一些错误

**Comment by muxinxy** [comment]
刚开始是这样
![image](https://user-images.githubusercontent.com/32673109/206627725-4a3ffdee-1ee7-493c-bbd8-33e7ca9afecd.png)
![image](https://user-images.githubusercontent.com/32673109/206627733-24a70f17-94e0-4f82-8803-f11e1c257260.png)
把0页的阅读时间20修改为200
![image](https://user-images.githubusercontent.com/32673109/206627833-5e502a93-a9cc-480e-a067-d2e0170c7d98.png)
再次阅读该文献，就会变成这样
![image](https://user-images.githubusercontent.com/32673109/206627852-a30a6cc2-1793-42de-99b1-f7c939f7e2bd.png)
一个是修改后的200，一个是25(20+5)

**Comment by MuiseDestiny** [comment]
修改成200后需要重启才会读取

**Comment by muxinxy** [comment]
重启之后没有读取，阅读相同文献还是会重新创建一条笔记
![image](https://user-images.githubusercontent.com/32673109/206634702-7fe358b7-611d-4a48-83dc-6086df19c34c.png)
![image](https://user-images.githubusercontent.com/32673109/206634729-25d5a9bf-fe87-4f71-a813-73ee05764f80.png)

**Comment by MuiseDestiny** [comment]
删除记录非200s的笔记，关闭Zotero，然后再打开，就会读取了。我没试过修改这个进度。

**Comment by muxinxy** [comment]
一共就一个笔记，删除了就是空的，重启zotero之后再次打开这篇文献还是从零开始

**Comment by MuiseDestiny** [comment]
新阅读的文章应该和chartero一致了的。但是我刚试了，确实可以修改的啊(修改完重启)，我意思是删除重复中的其中一个。我看你截图是两个”DIC-XXX“

**Comment by muxinxy** [comment]
修改前
![image](https://user-images.githubusercontent.com/32673109/206658887-0ecc8736-8973-43cc-bb09-37f040ae5549.png)
修改后
![image](https://user-images.githubusercontent.com/32673109/206658788-eb663d95-5d8d-427f-b208-d9b86a0eddfe.png)
重启后，未打开文献
![image](https://user-images.githubusercontent.com/32673109/206659261-0a4f4846-3349-437b-be5e-fdb2bfc5c5d0.png)
重启后，打开文献
![image](https://user-images.githubusercontent.com/32673109/206664285-c4853d45-6c3f-4058-b19d-596d7be7c3d8.png)
![image](https://user-images.githubusercontent.com/32673109/206664325-7b6136cc-1e17-484e-8de0-ba6586866f13.png)

**Comment by MuiseDestiny** [comment]
哈哈哈哈哈很详细，等我研究研究

**Comment by MuiseDestiny** [comment]
知道原因了，你修改之前，记录是json，一旦修改就变成
![image](https://user-images.githubusercontent.com/51939531/206688328-4cfa964a-e423-492c-bc8c-2a1b06342729.png)
html格式的了，插件无法正确读取解析数据，导致重新打开文献，笔记被重新创建。这是问题出现的原因，这一点我知道，我尽快处理。

**Comment by MuiseDestiny** [comment]
请更新解决这个问题，可能还会有重复的笔记，但不会归零了。现在也可以随意修改。

**Comment by muxinxy** [comment]
解决了，感谢！
