### ISSUE TITLE
带文字的自定义标签与纯emoji标签不对齐

### ISSUE THREAD

**Issue by Dirtyuri** [MuiseDestiny/ZoteroStyle#5]
如下图所示，紫色和深红色标签被我分配给文字了，有劳大大看下，感谢！

![1669344982983](https://user-images.githubusercontent.com/68465099/203891417-fd285cf6-eec3-49f6-8141-106cf3e6a01e.png)

![1669345016736](https://user-images.githubusercontent.com/68465099/203891473-7943e4bc-495b-4f90-8471-79201a2c1662.png)

![1669345049023](https://user-images.githubusercontent.com/68465099/203891481-d20c8dc2-2844-4dd1-90d4-9d02164f507e.png)

**Comment by MuiseDestiny** [comment]
感谢提出问题，我尽快解决

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/203944358-4f9cd6dc-3426-4bad-b326-1ae39662ae07.png)
但是这个不是我的锅，它本来也对不齐😄，但我会解决

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/203983287-fe29e2b1-cdcb-4f45-8fda-5d231bac1da0.png)
![image](https://user-images.githubusercontent.com/51939531/203983672-700044c7-1eaf-459c-846f-191b7426f453.png)
对齐了，等下一起发

**Comment by Dirtyuri** [comment]
好的好的，感谢！

**Comment by MuiseDestiny** [comment]
安装1.2.0
