### ISSUE TITLE
建议跟chartero结合一下

### ISSUE THREAD

**Issue by 1067237855** [MuiseDestiny/ZoteroStyle#6]
现在zoterostyle和chartero的阅读进度对应不起来（zoterostyle自己有一个阅读进度，chartero也有一个阅读进度），建议跟chartero结合一下。两者各有优势，两个插件如果可以合成一个就好了，功能互补。

**Comment by MuiseDestiny** [comment]
已经把这个进度条PR到Chartero了，可以等一下新版本。后面本插件可能会直接使用Chartero的文件渲染进度条不再单独设置监测函数，因为这与Chartero功能重复

**Comment by MuiseDestiny** [comment]
安装1.2.0可以与Chartero共存
