### ISSUE TITLE
能否加一个自定义移动标签位置？

### ISSUE THREAD

**Issue by coisini-95** [MuiseDestiny/ZoteroStyle#7]
插件默认是将所有标签放到论文名最后面，这样很美观，但是我觉得未读和已读的标签放到论文名前面更显眼一点，而且因为每个论文都会有这个标签，不是未读就是已读，也不会存在论文名对不齐的情况，所以要是能有一个移动标签位置的设置就更好了。
以上是我的一些看法，如果说的不对望作者大大见谅。

**Comment by MuiseDestiny** [comment]
可以，我也有想过，确实这样的设计与endnote就对应起来了，更容易阅读，感谢你的建议

**Comment by MuiseDestiny** [comment]
已经写好了，效果见readme，但还没发布等查找参考文献功能写好一起发

**Comment by coisini-95** [comment]
> 已经写好了，效果见readme，但还没发布等查找参考文献功能写好一起发

棒

**Comment by MuiseDestiny** [comment]
已发布，4个位置（极限了，不能再多了）随意摆布

**Comment by MuiseDestiny** [comment]
还能设置标签左对齐右对齐

**Comment by coisini-95** [comment]
> 已发布，4个位置（极限了，不能再多了）随意摆布

emmmm怎么指定单独某个标签在1的位置

**Comment by MuiseDestiny** [comment]
> > 已发布，4个位置（极限了，不能再多了）随意摆布
> 
> emmmm怎么指定单独某个标签在1的位置

我理解你意思，也可以实现，但是不太好提供设置，你是想单独把已读未读放最左边，其他标签右边是吗

**Comment by coisini-95** [comment]
> > > 已发布，4个位置（极限了，不能再多了）随意摆布
> > 
> > 
> > emmmm怎么指定单独某个标签在1的位置
> 
> 我理解你意思，也可以实现，但是不太好提供设置，你是想单独把已读未读放最左边，其他标签右边是吗

嗯嗯

**Comment by coisini-95** [comment]
![图片](https://user-images.githubusercontent.com/78250635/204314571-01a25ffa-3a31-4f92-88f5-7d8d543541a1.png)
![图片](https://user-images.githubusercontent.com/78250635/204314597-5cf0c3cc-a7b4-4f5a-bd26-b59bbd8e12e8.png)
![图片](https://user-images.githubusercontent.com/78250635/204314632-203210d0-9db4-4acc-be2a-b2e5e225275c.png)
![图片](https://user-images.githubusercontent.com/78250635/204314720-2a4b6773-fc0c-4cf9-b5e6-6878e0e7a3b9.png)
这个命令是啥效果哇，怎么只是左下角标签位置变了

**Comment by MuiseDestiny** [comment]
> ![图片](https://user-images.githubusercontent.com/78250635/204314571-01a25ffa-3a31-4f92-88f5-7d8d543541a1.png) ![图片](https://user-images.githubusercontent.com/78250635/204314597-5cf0c3cc-a7b4-4f5a-bd26-b59bbd8e12e8.png) ![图片](https://user-images.githubusercontent.com/78250635/204314632-203210d0-9db4-4acc-be2a-b2e5e225275c.png) ![图片](https://user-images.githubusercontent.com/78250635/204314720-2a4b6773-fc0c-4cf9-b5e6-6878e0e7a3b9.png) 这个命令是啥效果哇，怎么只是左下角标签位置变了

用于改变颜色，”#xxxx“是颜色，可以在<https://colorhunt.co/>找喜欢的颜色，Zotero默认9个颜色，这么设置可以取无限颜色

**Comment by coisini-95** [comment]
> > ![图片](https://user-images.githubusercontent.com/78250635/204314571-01a25ffa-3a31-4f92-88f5-7d8d543541a1.png) ![图片](https://user-images.githubusercontent.com/78250635/204314597-5cf0c3cc-a7b4-4f5a-bd26-b59bbd8e12e8.png) ![图片](https://user-images.githubusercontent.com/78250635/204314632-203210d0-9db4-4acc-be2a-b2e5e225275c.png) ![图片](https://user-images.githubusercontent.com/78250635/204314720-2a4b6773-fc0c-4cf9-b5e6-6878e0e7a3b9.png) 这个命令是啥效果哇，怎么只是左下角标签位置变了
> 
> 用于改变颜色，”#xxxx“是颜色，可以在https://colorhunt.co/找喜欢的颜色，Zotero默认9个颜色，这么设置可以取无限颜色

哦哦，我还以为是又能改变位置又能改变颜色呢
