### ISSUE TITLE
阅读进度两个设备无法同步

### ISSUE THREAD

**Issue by batman47steam** [MuiseDestiny/ZoteroStyle#8]
很棒的插件，显示阅读进度的那个功能很喜欢，感觉很简约很nice，但是好像在两个设备上没办法同步，实验室的台式机上的阅读进度在另外一台电脑上好像就没有了

**Comment by MuiseDestiny** [comment]
Chartero将记录保存到笔记（这个笔记似乎可以同步），高能进度条我已经加入到Chartero里了，可以尝试一下，或许可以解决你的同步问题。

**Comment by MuiseDestiny** [comment]
https://gitee.com/const_volatile/chartero

**Comment by batman47steam** [comment]
好的，我去看看

**Comment by MuiseDestiny** [comment]
安装1.2.0可以与Chartero共存
