### ISSUE TITLE
进度条消失

### ISSUE THREAD

**Issue by batman47steam** [MuiseDestiny/ZoteroStyle#9]
我安装了最新的zoterostyle和chartzotero那个，但是每次chartzotero刷新出来的进度只要点击一下就消失了，不知道是为什么

https://user-images.githubusercontent.com/36287035/204091040-3e3a061c-2e94-4104-b488-9a3101d06e55.mp4

**Comment by batman47steam** [comment]
把chartero给disable掉，能够正常的显示进度条。但是如果和chartero一起，每次点击chartero的图标可以刷新出进度条，但是如果一点条目，刷新出来的进度条就立刻消失了

**Comment by MuiseDestiny** [comment]
是这样，style渲染是改了zotero的渲染函数，chartero的渲染是往页面添加进度条，当你点击条目时候会触发zotero的渲染，而其本身是没有进度条的。所以才会出现你视频中的情况。

**Comment by batman47steam** [comment]
这个有啥解决方法吗

**Comment by MuiseDestiny** [comment]
> 这个有啥解决方法吗

你想要什么样的

**Comment by batman47steam** [comment]
就是能够显示进度条，而且点击不会消失的，然后要是能够同步就完美了，用chartero主要就是想利用同步的功能

**Comment by batman47steam** [comment]
回退到1.1.5以后点击也不会消失了，但能不能同步还没测试，好像记得说是1.1.5以后渲染进度条的部分全部交给chartero了，是不是因为这个原因？1.1.5的版本还是在自己独立的渲染进度条，所以点击也不会消失

**Comment by Mashmall** [comment]
希望可以增加默认显示阅读进度的开关嘛 合并给chatero之后 每次需要手动刷新很不直观，或指北修改源代码 满足一下我这小众需求，谢谢

**Comment by MuiseDestiny** [comment]
> 希望可以增加默认显示阅读进度的开关嘛 合并给chatero之后 每次需要手动刷新很不直观，或指北修改源代码 满足一下我这小众需求，谢谢

记下了

**Comment by MuiseDestiny** [comment]
实现了，请更新测试~
